/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.vanderbilt.cs.live9.car;

import java.util.List;

public interface Car {
	
  
	public Status start();
	public Status stop();
	
	public Engine getEngine();
	public List<Wheel> getWheels();
	
	public void applyGas(int gasPedalPosition) ;
	
}
